name: student_application_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.3
  email_validator: ^3.0.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  percent_indicator: ^4.2.4
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
